version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "."
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 50
